sudo: required
services:
  - docker
before_install:
  - docker build -t gmahe/react-test -f ./client/Dockerfile.dev ./client
script:
  - docker run -e CI=true gmahe/react-test npm run test
# Production versions
after_success:
  - docker build -t gmahe/multi-client ./client
  - docker build -t gmahe/multi-nginx ./nginx
  - docker build -t gmahe/multi-server ./server
  - docker build -t gmahe/multi-worker ./worker
  # Login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push to dockerhub
  - docker push gmahe/multi-nginx
  - docker push gmahe/multi-client
  - docker push gmahe/multi-server
  - docker push gmahe/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-eu-west-2-526137194484"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
